name: 'data_catalog_dbt'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.7.0"
profile: 'data_catalog_dbt'
model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  pii_sensitive_policy_tag_id: "{{ env_var('PII_SENSITIVE_POLICY_TAG_ID') }}" # Or use a different method to get the ID from Terraform output
  non_pii_sensitive_policy_tag_id: "{{ env_var('NON_PII_SENSITIVE_POLICY_TAG_ID') }}" # Or use a different method to get the ID from Terraform output