data_catalog_dbt:
  target: dev  # You can change this to 'acc', 'prd', or another target later
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "gcp-data-catalog-terraform/terraform-sa-key.json" # Replace with the actual path to your service account key file 
      #keyfile: "{{ env_var('DEV_DATA_CATALOG_KEY') }}" # or you can use a git variable, which you need to initi
      project: gcp-data-governance  # Replace with your GCP project ID
      dataset: multiplexer_dataset # Replace with your BigQuery dataset name
      location: europe-west6 # Or your BigQuery location
      threads: 6
  