data_catalog_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "gcp-data-governance" #priject_id
      dataset: multiplexer_dataset
      threads: 4
      keyfile: "/path/to/dbt-sa-key.json" 
      location: "europe-west6"  # Set this to your BigQuery region
