data_catalog_dbt:
  target: dev  # You can change this to 'acc', 'prd', or another target later
  outputs:
    dev:
      type: bigquery
      method: service-account
      #keyfile: "/path/to/your/service_account_key.json" # Replace with the actual path to your service account key file 
      keyfile: "{{ env_var('DEV_DATA_CATALOG_KEY') }}" # or you can use a git variable, which you need to initi
      project: your-gcp-project-id  # Replace with your GCP project ID
      dataset: your_bigquery_dataset # Replace with your BigQuery dataset name
      location: europe-west6 # Or your BigQuery location
      threads: 6
  
      