data_catalog_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"  # Ensure this is set
      dataset: multiplexer_dataset
      threads: 4
      keyfile: "{{ env_var('DEV_DATA_CATALOG_KEY') }}"  # Reference your environment variable
      location: "europe-west6"  # Set this to your BigQuery region
